language: python
python:
  - "3.8"
install:
  - pip install .
  - pip install -r requirements.txt
  - pip install coverage
  - pip install codecov
script:
  - flake8 --ignore=E501,W605
  - coverage run -m  pytest -q test/
after_success:
  - bash <(curl -s https://codecov.io/bash) -t c18f2a5b-6240-4bec-a551-b427163f05b8


